"""add_chat_summary_fields

Revision ID: 1578dc4794bb
Revises: aca5bd3b31cf
Create Date: 2026-02-19 13:05:00.273750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1578dc4794bb'
down_revision = 'aca5bd3b31cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
