"""add_chat_summary_fields

Revision ID: 20b80069323a
Revises: 1578dc4794bb
Create Date: 2026-02-19 13:13:49.157170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b80069323a'
down_revision = '1578dc4794bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('summary', sa.String(length=2000), nullable=True, comment='LLM-generated session summary'))
    op.add_column('chat_sessions', sa.Column('summary_updated_at', sa.DateTime(), nullable=True, comment='Last summary update timestamp'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'summary_updated_at')
    op.drop_column('chat_sessions', 'summary')
    # ### end Alembic commands ###
