"""add_chat_summary_fields

Revision ID: aca5bd3b31cf
Revises: 002_chat_history
Create Date: 2026-02-19 13:03:59.103448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca5bd3b31cf'
down_revision = '002_chat_history'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
